### ISSUE TITLE
ckpts/bigvgan_24khz_100band\\config.json

### ISSUE THREAD

**Issue by scientistdanyal** [DiffPitcher/DiffPitcher#1]
FileNotFoundError: [Errno 2] No such file or directory: 'ckpts/bigvgan_24khz_100band\\config.json'

**Comment by haidog-yaqub** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'ckpts/bigvgan_24khz_100band\config.json'

Hello, I have updated the ckpts in Google Drive, please download them and place them in the ckpts folder.

**Comment by scientistdanyal** [comment]
I updated the ckeckpoints (ckpts) but still i am getting this error

(myenv) PS E:\DiffPitcher> python .\template_based_apc.py
E:\DiffPitcher\myenv\Lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
ckpts/bigvgan_24khz_100band/g_05000000
E:\DiffPitcher\myenv\Lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "E:\DiffPitcher\template_based_apc.py", line 85, in <module>
    hifigan, cfg = load_model(hifi_path, device=device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DiffPitcher\pitch_controller\modules\BigVGAN\inference.py", line 30, in load_model
    cp_dict = torch.load(model_path, map_location=device)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DiffPitcher\myenv\Lib\site-packages\torch\serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DiffPitcher\myenv\Lib\site-packages\torch\serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DiffPitcher\myenv\Lib\site-packages\torch\serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ckpts/bigvgan_24khz_100band/g_05000000'

**Comment by scientistdanyal** [comment]
File "E:\DiffPitcher\template_based_apc.py", line 85, in <module>
    hifigan, cfg = load_model(hifi_path, device=device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DiffPitcher\pitch_controller\modules\BigVGAN\inference.py", line 30, in load_model
    cp_dict = torch.load(model_path, map_location=device)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DiffPitcher\myenv\Lib\site-packages\torch\serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DiffPitcher\myenv\Lib\site-packages\torch\serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DiffPitcher\myenv\Lib\site-packages\torch\serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'ckpts/bigvgan_24khz_100band/g_05000000'
